experiment_name: SmokeDetection
run_name: bayes
test_run: true
shuffle: true
subset: null
use_outlines: false
num_epochs: 1
threshold: 0.9940672544464014
oversample: true
seed: 123
outliers_numb: 10
hyperparams:
    var_smoothing: 1.06471030620842e-06
