experiment_name: SmokeDetection
run_name: bayes
test_run: true
shuffle: true
subset: null
use_outlines: false
num_epochs: 1
threshold: 0.994067843627874
oversample: true
seed: 123
outliers_numb: 6
hyperparams:
    var_smoothing: 1e-08
