defaults:
  - _self_
  - dataset: SmokeDefault
  - model: Naive
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: colorlog
  - override hydra/sweeper: optuna
hydra:
  run:
    dir: ${hydra:runtime.cwd}/storage/hydra_output
  sweep:
    dir: ./storage/hydra_multirun
    subdir: ${now:%Y-%m-%d_%H-%M}/${hydra.job.num}
  sweeper:
    sampler:
      seed: ${model.seed}
    direction: maximize
    study_name: ${secret.study_name}
    storage: null
    n_trials: 34
    n_jobs: 1
    params:
      model.hyperparams.var_smoothing: choice(1e-12, 1e-11, 1e-10, 1e-9, 1e-8)
      model.outliers_numb: range(1, 12)
secret:
  kaggle: kaggle.json
  secrets: secrets.json
  study_name: optimization
path:
  base: ${hydra:runtime.cwd}
  config: ${path.base}/config
  data: ${path.base}/data
  storage: ${path.base}/storage
  model_registry: ${path.storage}/model
  results: ${path.base}/results
  log: ${path.base}/logs
  why_logs: ${path.storage}/whylogs
